var sangarSetupBulletNav;
(function(e){sangarSetupBulletNav=function(b,a){b.setupBulletNav=function(){b.$sangarWrapper.append("bullet"==a.pagination?'<ul class="sangar-pagination sangar-pagination-'+a.pagination+'"></ul>':'<ul class="sangar-pagination sangar-pagination-'+a.pagination+" sangar-pagination-type-"+a.paginationContentType+'"></ul>');b.$pagination=b.$sangarWrapper.children("ul.sangar-pagination");for(i=0;i<b.numberSlides;i++){var c;switch(a.pagination){case "bullet":c=1==a.paginationBulletNumber?e('<li class="sangar-slideshow-nav-pagination sangar-bullet-number">'+
(i+1)+"</li>"):e('<li class="sangar-slideshow-nav-pagination"></li>');break;case "content-horizontal":if("text"==a.paginationContentType)c=0<a.paginationContent.length?a.paginationContent[i]:"",c=e('<li class="sangar-slideshow-nav-pagination">'+c+"</li>");else if("image"==a.paginationContentType){c="undefined"!=typeof a.paginationContent[i]?a.paginationContent[i]:"";var f="undefined"!=typeof a.paginationImageAttr[i]?a.paginationImageAttr[i]:"";c=e('<li class="sangar-slideshow-nav-pagination"><div><img src="'+
c+'" '+f+' width="'+a.paginationContentWidth+'" height="'+a.paginationImageHeight+'"></div></li>')}break;case "content-vertical":"text"==a.paginationContentType?(c=0<a.paginationContent.length?a.paginationContent[i]:"",c=e('<li class="sangar-slideshow-nav-pagination">'+c+"</li>")):"image"==a.paginationContentType&&(c="undefined"!=typeof a.paginationContent[i]?a.paginationContent[i]:"",f="undefined"!=typeof a.paginationImageAttr[i]?a.paginationImageAttr[i]:"",c=e('<li class="sangar-slideshow-nav-pagination"><img src="'+
c+'" '+f+' width="'+a.paginationContentWidth+'" height="'+a.paginationImageHeight+'"></li>'));break;default:c=e('<li class="sangar-slideshow-nav-pagination"></li>')}b.$sangarWrapper.children("ul.sangar-pagination").append(c);c.data("index",i);c.click(function(){b.stopSliderLock();b.shift(e(this).data("index"))})}b.$pagination.wrap("<div class='sangar-pagination-wrapper wrapper-"+a.pagination+"' />");"bullet"==a.pagination&&"autohide"==a.directionalNav&&(b.$pagination.css("opacity",a.directionalNavHideOpacity),
b.$sangarWrapper.mouseenter(function(){b.$pagination.stop(!0,!0);b.$pagination.animate({opacity:a.directionalNavShowOpacity},300)}),b.$sangarWrapper.mouseleave(function(){b.$pagination.stop(!0,!0);b.$pagination.animate({opacity:a.directionalNavHideOpacity},300)}))};b.setBulletPosition=function(){if("bullet"==a.pagination){var c=b.$pagination.children("li"),f=c.outerWidth()*b.numberSlides,t=0;c.each(function(a){a=e(this).css("margin-left").slice(0,-2);var b=e(this).css("margin-right").slice(0,-2);
isNaN(a)&&(a=0);isNaN(b)&&(b=0);t=t+parseInt(a)+parseInt(b)});f+=t;"vertical-slide"==a.animation?(b.$pagination.parent().css({top:"50%","margin-top":"-"+f/2+"px",bottom:"0px",right:"12px"}),c.css({"float":"none","margin-left":"0px","margin-top":"10px"}),c.first().css("margin-top","0px")):b.$pagination.parent().css({left:"50%","margin-left":"-"+f/2+"px"})}else if("content-horizontal"==a.pagination){var c=b.$pagination.parent(".sangar-pagination-wrapper"),f=100*a.paginationContentOpacity,d=b.sangarHeight,
z=parseInt(c.outerHeight()),d=d-z;b.$sangarWrapper.find(".sangar-textbox").css("height",d+"px");c.css({opacity:a.paginationContentOpacity,filter:"alpha(opacity="+f+")"})}};b.setupSliderBulletNav=function(){function c(a,b,c){"sliding_one"==a?1==A&&(d.children("li").removeClass("sangar-bullet-sliding-one-back").removeClass("sangar-bullet-sliding-one-next"),a=d.children("li").eq(c),"sangar-slideshow-nav-pagination"==a.attr("class")&&a.addClass(b)):"sliding"==a&&("sangar-slideshow-nav-pagination sangar-pagination-active"==
d.children("li").eq(c).attr("class")&&0<c&&("sangar-bullet-sliding-back"==b?c--:"sangar-bullet-sliding-next"==b&&c++),d.children("li").eq(c).removeClass("sangar-bullet-sliding-one-back"),d.children("li").eq(c).removeClass("sangar-bullet-sliding-one-next"),d.children("li").eq(c).addClass(b))}function f(a){var b=0;d.children("li").removeClass("sangar-bullet-sliding-one-back").removeClass("sangar-bullet-sliding-one-next");"back"==a?(d.children("li").eq(g-1).addClass("sangar-bullet-sliding-one-next"),
b=w-k):(d.children("li").eq(l+1).addClass("sangar-bullet-sliding-one-back"),b=w+k);w=b;t(w)}function t(c){var e="vertical"==p?"translate3d(0, -"+c+"px, 0)":"translate3d(-"+c+"px, 0, 0)";z<m&&(b.css3support()?(c={},c["-"+b.vendorPrefix+"-transition-duration"]=a.animationSpeed+"ms",c["-"+b.vendorPrefix+"-transform"]=e,d.css(c)):d.animate({direction:"-"+c+"px"},a.animationSpeed))}var d=0,z=0,u=0,v=0,q=0,l=0,g=0,k=0,n=0,A=!1,r=0,x=0,w=0,h=a.paginationContentWidth,m=h*b.numberSlides,m="image"==a.paginationContentType?
m+5*b.numberSlides:m,y=0,B=0,p=a.pagination,p=p.substring(8);"horizontal"==p&&(d=b.$sangarWrapper.find("ul.sangar-pagination-"+a.pagination),d.width(m));this.generateSlideBullet=function(){d=b.$sangarWrapper.find("ul.sangar-pagination-"+a.pagination);var c=d.parent().outerWidth(!0);z=c;n=k=g=l=q=v=u=0;A=!1;d.parent().css("overflow","hidden");d.css("background-color",d.children("li").last().css("background-color"));d.children("li.sangar-slideshow-nav-pagination").css("width",h+"px");"vertical"==p?
(y=d.children("li").outerHeight(),B=y*b.numberSlides,d.css("width",h+"px"),d.parent().css({width:h+"px",right:"0px",height:b.sangarHeight+"px"}),b.$el.css({height:b.sangarHeight+"px"}),b.$sangar.css({"margin-left":"0px"})):d.width(m);"vertical"==p?(x=b.sangarHeight,x>B&&(x=B)):(r=c,r>m&&(a.paginationContentFullWidth?(h=r/b.numberSlides,m=h*b.numberSlides):r=m));(function(){d.find("li").each(function(){if("vertical"==p){if(v+=y,v+y>x&&(q=g=e(this).index()),v>x)return e(this).addClass("sangar-bullet-sliding-next"),
k=v-x,k<y&&(A=!0),!1}else if(u+=h,u+h>r&&(q=g=e(this).index()),u>r)return e(this).addClass("sangar-bullet-sliding-next"),k=u-r,k<h&&(A=!0),!1})})()};this.slideBullet=function(a){var e="vertical"==p?y:h,f=0;"next"==a?(d.children("li").eq(b.numberSlides-1).hasClass("sangar-bullet-sliding-next")||(d.children("li").removeClass("sangar-bullet-sliding-back").removeClass("sangar-bullet-sliding-next"),n++,l++,g++),f=e*n+k,c("sliding_one","sangar-bullet-sliding-one-back",l+1)):"back"==a?(d.children("li").removeClass("sangar-bullet-sliding-back").removeClass("sangar-bullet-sliding-next"),
n--,l--,g--,f=e*n,c("sliding_one","sangar-bullet-sliding-one-next",g-1)):"first"==a?(d.children("li").removeClass("sangar-bullet-sliding-back").removeClass("sangar-bullet-sliding-next"),l=n=0,g=q,f=e*n,c("sliding_one","sangar-bullet-sliding-one-next",g-1)):"last"==a&&(d.children("li").removeClass("sangar-bullet-sliding-back").removeClass("sangar-bullet-sliding-next"),a=b.numberSlides-1,n=a-q,l=a-q,g=a,f=e*n+k,c("sliding_one","sangar-bullet-sliding-one-back",l+1));w=f;t(w);c("sliding","sangar-bullet-sliding-back",
l);c("sliding","sangar-bullet-sliding-next",g)};this.setActiveBullet=function(){if("none"==a.pagination)return!1;b.$pagination.children("li").removeClass("sangar-pagination-active").eq(b.activeSlide).addClass("sangar-pagination-active");"content-horizontal"!=a.pagination&&"content-vertical"!=a.pagination||this.beginSlideBullet()};this.beginSlideBullet=function(){var a=b.$pagination.children("li.sangar-pagination-active"),c=0==a.index()?!0:!1,d=0<a.index()?!0:!1,e=a.index()==b.numberSlides-1?!0:!1;
a.hasClass("sangar-bullet-sliding-next")?e?this.slideBullet("last"):this.slideBullet("next"):a.hasClass("sangar-bullet-sliding-back")?d?this.slideBullet("back"):this.slideBullet("first"):a.hasClass("sangar-bullet-sliding-one-next")?f("next"):a.hasClass("sangar-bullet-sliding-one-back")?f("back"):0<q&&(c?this.slideBullet("first"):e&&this.slideBullet("last"))}}}})(jQuery);