var sangarShift;
(function(l){sangarShift=function(a,d){a.shift=function(g){a.beforeSlideChange();a.prevActiveSlide=a.activeSlide;a.slideDirection=g;if(a.prevActiveSlide==g)return!1;if(!a.locked){a.lock();if("next"==g)a.activeSlide++,a.activeSlideContinous++,a.activeSlide==a.numberSlides&&(a.activeSlide=0);else if("prev"==g)a.activeSlide--,a.activeSlideContinous--,0>a.activeSlide&&(a.activeSlide=a.numberSlides-1);else{for(var f=a.activeSlideContinous%a.numberSlides,b=a.activeSlideContinous-f,c=0;c<g&&(b++,c!=g);c++);
0>a.activeSlideContinous&&0!=f&&(b-=a.numberSlides);a.activeSlideContinous=b;a.activeSlide=g}a.bulletObj.setActiveBullet();a.setCurrentSlide();if("horizontal-slide"==d.animation)if(d.continousSliding){var b=a.sangarWidth*a.activeSlideContinous,f=-1*b,c=a.$slideWrapper.children(".slideWrapperInside"),c=c.children(".sangar-content"),h=c.width()*a.numberSlides,c=a.$slideWrapper.children(".slideWrapperInside.swi1st"),k=a.$slideWrapper.children(".slideWrapperInside.swi2nd"),e=a.$slideWrapper.children(".slideWrapperInside.swi3rd");
"next"==g&&0==a.activeSlide?(c.addClass("notransition"),c.css("margin-left",b+h+"px"),c.removeClass("swi1st").addClass("swi3rd"),k.removeClass("swi2nd").addClass("swi1st"),e.removeClass("swi3rd").addClass("swi2nd"),c[0].offsetHeight,c.removeClass("notransition")):"prev"==g&&a.activeSlide==a.numberSlides-1&&(e.addClass("notransition"),e.css("margin-left",b-h-(h-a.sangarWidth)+"px"),c.removeClass("swi1st").addClass("swi2nd"),k.removeClass("swi2nd").addClass("swi3rd"),e.removeClass("swi3rd").addClass("swi1st"),
e[0].offsetHeight,e.removeClass("notransition"));a.css3support()?(b={},b["-"+a.vendorPrefix+"-transition"]=d.animationSpeed+"ms cubic-bezier(0.445, 0.05, 0.55, 0.95)",b["-"+a.vendorPrefix+"-transform"]="translate("+f+"px, 0)",b["-"+a.vendorPrefix+"-transform-style"]="preserve-3d",b["-"+a.vendorPrefix+"-backface-visibility"]="hidden",b["-"+a.vendorPrefix+"-perspective"]="1000px",a.$slideWrapper.css(b)):a.$slideWrapper.animate({left:f+"px"},d.animationSpeed);d.carousel&&(a.doBlur(".swi2nd",a.activeSlide,
1),a.doBlur(".swi2nd",a.prevActiveSlide,d.carouselOpacity),0==a.prevActiveSlide&&a.doBlur(".swi3rd",a.prevActiveSlide,d.carouselOpacity),a.prevActiveSlide==a.numberSlides-1&&a.doBlur(".swi1st",a.prevActiveSlide,d.carouselOpacity))}else f=a.sangarWidth*a.activeSlide<a.numberSlides*a.sangarWidth?"-"+a.sangarWidth*a.activeSlide:0,a.css3support()?(b={},b["-"+a.vendorPrefix+"-transition"]=d.animationSpeed+"ms cubic-bezier(0.445, 0.05, 0.55, 0.95)",b["-"+a.vendorPrefix+"-transform"]="translate("+f+"px, 0)",
b["-"+a.vendorPrefix+"-transform-style"]="preserve-3d",b["-"+a.vendorPrefix+"-backface-visibility"]="hidden",b["-"+a.vendorPrefix+"-perspective"]="1000px",a.$slideWrapper.css(b)):a.$slideWrapper.animate({left:f+"px"},d.animationSpeed);"vertical-slide"==d.animation&&(d.continousSliding?(b=a.sangarHeight*a.activeSlideContinous,f=-1*b,c=a.$slideWrapper.children(".slideWrapperInside"),c=c.children(".sangar-content"),h=c.height()*a.numberSlides,c=a.$slideWrapper.children(".slideWrapperInside.swi1st"),
k=a.$slideWrapper.children(".slideWrapperInside.swi2nd"),e=a.$slideWrapper.children(".slideWrapperInside.swi3rd"),"next"==g&&0==a.activeSlide?(c.addClass("notransition"),c.css("margin-top",b+h+"px"),c.removeClass("swi1st").addClass("swi3rd"),k.removeClass("swi2nd").addClass("swi1st"),e.removeClass("swi3rd").addClass("swi2nd"),c[0].offsetHeight,c.removeClass("notransition")):"prev"==g&&a.activeSlide==a.numberSlides-1&&(e.addClass("notransition"),e.css("margin-top",b-h-(h-a.sangarHeight)+"px"),c.removeClass("swi1st").addClass("swi2nd"),
k.removeClass("swi2nd").addClass("swi3rd"),e.removeClass("swi3rd").addClass("swi1st"),e[0].offsetHeight,e.removeClass("notransition"))):f=a.sangarHeight*a.activeSlide<a.numberSlides*a.sangarHeight?"-"+a.sangarHeight*a.activeSlide:0,a.css3support()?(b={},b["-"+a.vendorPrefix+"-transition"]=d.animationSpeed+"ms cubic-bezier(0.445, 0.05, 0.55, 0.95)",b["-"+a.vendorPrefix+"-transform"]="translate(0, "+f+"px)",b["-"+a.vendorPrefix+"-transform-style"]="preserve-3d",b["-"+a.vendorPrefix+"-backface-visibility"]=
"hidden",b["-"+a.vendorPrefix+"-perspective"]="1000px",a.$slideWrapper.css(b)):a.$slideWrapper.animate({top:f+"px"},d.animationSpeed));"fade"==d.animation&&(a.$slides.eq(a.prevActiveSlide).css({opacity:1,"z-index":2}).animate({opacity:0},d.animationSpeed),a.$slides.eq(a.activeSlide).css({opacity:0,"z-index":3}).animate({opacity:1},d.animationSpeed));a.resetAndUnlock()}}}})(jQuery);